version: '3'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: "treasure_hunter_app_1"
    volumes:
      - .:/treasure_hunter
    ports:
      - "7001:3000"
    networks:
      - treasure_hunter_network
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
  # db:
  #   image: "mysql:5.7"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - ./.docker/mysql:/var/lib/mysql
  #   ports:
  #      - "3306"
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - treasure_hunter_network
  redis:
    image: redis
    networks:
      - treasure_hunter_network
    ports:
      - "6379"
networks:
  treasure_hunter_network:
