database:
  database_name: 'treasure_hunter_development'
  host: 'db'
  port: 3306
  username: 'root'
  password: 'root'
aws:
  s3:
    preserve_files: false
    s3_host_name: 's3-us-west-1.amazonaws.com'
    access_key_id: '123'
    secret_access_key: '23344'
    s3_region: 'us-west-1'
    bucket: 'test-2'
    prefix: 'dev/'
domain_name: "http://localhost:7003"
redis_cache:
  redis_uri: "redis://redis:6379/3"
locker:
  redis_uri: "redis://redis:6379/4"
sidekiq:
  redis_uri: "redis://redis:6379/5"
  basic_auth:
    username: 'sidekiq'
    password: '1234'
unifonic_cloud:
  base_url: "https://cloud.unifonic.com"
  client_id: '123'
  client_secret: '21341'
  auth_url: 'https://cloud.unifonic.com/oauth/v2/auth?response_type=code&client_id=%{client_id}&redirect_uri=%{redirect_uri}'
  logout_url: 'https://cloud.unifonic.com/logout'
  me_url: 'https://cloud.unifonic.com/app/api/v2/user/me'
nextgen:
  base_url: 'http://95.177.221.161:13001'
  secret_key: '123'
  enabled: false
client_app_requests_origin: 'localhost:4202'
disable_permission_check:
  all: false
frontend:
  check_login: 'http://localhost:4202/check_login'
  home_url: 'http://localhost:4202'
sms:
  base_url: 'http://basic.unifonic.com'
voice:
  base_url: 'http://basic.unifonic.com'
  pre_sound:
    ar: 'https://utilities-storage.s3.amazonaws.com/voice-pre-sounds/ar.wav'
    en: 'https://utilities-storage.s3.amazonaws.com/voice-pre-sounds/en.wav'
mailer:
  host: "mailcatcher"
  port: "1025"
  domain: "http://localhost:7071"
  authentication: "plain"
  user_name: ""
  password: ""
  from_email: "admin@unifo.com"
  exception_alert:
    - ahussain@unifonic.com
channels:
  active:
    sms: true
    voice: false
