# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: postgresql
  encoding: unicode
  reconnect: false
  timeout: 5000
  pool: 50
  host: 'db'
  port: 5432
  username: postgres
  password: root

development:
  <<: *default
  database: treasure_hunter_development

test:
  <<: *default
  database: treasure_hunter_test

production:
  <<: *default
  url: ENV['DATABASE_URL']
  # database: treasure_hunter_production
  # username: postgres
  # password: root
